name: CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t zeph1rrinc/sound-producer-server:$(cat version.txt) .

      - name: Check images
        run: docker images | grep $(cat version.txt)

      - name: Log in docker hub
        run: docker login -u zeph1rrinc -p ${{secrets.DOCKER_HUB_PASS}}

      - name: Push image
        run: docker push zeph1rrinc/sound-producer-server:$(cat version.txt)